version: '3.5'

services:
    backend:
        container_name: nest-api
        build:
            context: .
            dockerfile: ./deployment/back/Dockerfile
        ports:
            - 9000:9000
            - 8000:8000
        depends_on:
            - db
        restart: unless-stopped
        stop_grace_period: 1s
        networks:
            - front-network
            - back-network
        env_file: ./deployment/back/.env

    frontend:
        container_name: front
        build:
            context: .
            dockerfile: ./deployment/front/Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
        restart: unless-stopped
        stop_grace_period: 1s
        networks:
            - front-network
        env_file: ./deployment/back/.env
    db:
        container_name: db
        restart: unless-stopped
        stop_grace_period: 1s
        image: postgres:12.10
        volumes:
            - database:/var/lib/postgresql/data
        env_file: ./deployment/back/.env
        ports:
            - 5555:5432
        networks:
            - back-network
        
volumes:
    database: {}

networks:
    front-network:
    back-network:
